### ISSUE TITLE
Problems changing driver

### ISSUE THREAD

**Issue by Digaoo** [xenpac/sun4i_csi#1]
Hi, I've been trying to find a better driver for the Ov5640 camera for a few months now and although I found a few alternatives I've been having problems on how to use them, what I mean is for using an alternative such as the one on this repository should I try to insmod the solution or compile a new kernel altogether ?

**Comment by xenpac** [comment]
yes normally you will integrate this code as a replacement of the existing directory sun4i_csi
and then complie the kernel.
i added the .ko files. maybe just copying them to the relevant location may do the trick.
